version: '3.8'

services:
  voip-answering-machine:
    image: docker pull ghcr.io/nerdscorp/voip-answering-machine:latest
    #image: docker pull ghcr.io/nerdscorp/voip-answering-machine:Dev
    ports:
      - "5060:5060/udp"  # SIP
      - "10000-10001:10000-10001/udp"  # RTP
    volumes:
      - ./recordings:/var/spool/asterisk/recording
      - ./logs:/var/log/asterisk
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - EMAIL_TO=recipient@gmail.com
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/YOUR_WEBHOOK_URL
    restart: unless-stopped
